# PSM-managed SNI stream config
# Generated by PSM — do not edit manually

map $ssl_preread_server_name $psm_backend {
    # PSM:ENTRIES:BEGIN
    # PSM:ENTRIES:END
    default     127.0.0.1:{{REALITY_PORT}};
}

server {
    listen 443 reuseport;
    listen [::]:443 reuseport;
    proxy_pass $psm_backend;
    ssl_preread on;
    proxy_connect_timeout 5s;
}
