# PSM-managed SNI config
# Generated by PSM — do not edit manually
#
# 未知 SNI 一律黑洞（空 upstream → proxy_pass 解析失败 → 直接断连，零回源流量）。
# 绝不可把 default 指向 Reality：Reality 会把认证未通过的连接原样转发给 dest，
# 那等于让任何人都能拿本机当免费中继。已挂载节点各有显式条目，不依赖 default。

map $ssl_preread_server_name $psm_backend {
    # PSM:ENTRIES:BEGIN
    # PSM:ENTRIES:END
    default     "";
}

server {
    listen 443 reuseport;
    listen [::]:443 reuseport;
    proxy_pass $psm_backend;
    ssl_preread on;
    proxy_connect_timeout 5s;
}
